matrix:
  include:
    - language: go
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.43.0
        - golangci-lint run
        - go test ./...
      go:
        - 1.17.x
    - language: node_js
      node_js: 10
      script:
        - cd jirabot
        - yarn
        - yarn ci
