matrix:
  include:
    - language: go
      script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0
        - golangci-lint run --timeout 10m
        - go test ./...
      go:
        - 1.19.x
    - language: node_js
      node_js: 10
      script:
        - cd jirabot
        - yarn
        - yarn ci
