matrix:
  include:
    - language: go
      env:
        - GO111MODULE=on
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.23.6
        - golangci-lint run
        - go test ./...
      go:
        - 1.13.x
    - language: node_js
      node_js: 10
      script:
        - cd jirabot
        - yarn
        - yarn ci
